workflows:
  ci:
    name: CI
    max_build_duration: 120
    instance_type: mac_mini_m1

    triggering:
      events:
        - push

    environment:
      flutter: stable
      xcode: 15.3

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Run tests
        script: flutter test

      - name: Run integration tests
        script: |
          flutter -v emulators --launch apple_ios_simulator
          flutter -v test integration_test/main_test.dart -d iPhone
