workflows:
  ci:
    name: CI
    max_build_duration: 120
    instance_type: mac_mini_m1

    triggering:
      events:
        - push

    environment:
      flutter: stable
      xcode: 15.3

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Run tests
        script: flutter test

      - name: /usr/bin/arch -arm64e xcrun simctl list devices booted
        script: /usr/bin/arch -arm64e xcrun simctl list devices booted

      - name: Launch iOS simulator
        script: flutter -v emulators --launch apple_ios_simulator

      - name: Run integration tests
        script: flutter -v test integration_test/main_test.dart -d iPhone
