name: CI

on:
  push:

jobs:
  ci:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        working-directory: ios
        run: pod install

      - name: Run Integration Tests
        run: |
          flutter -v emulators --launch apple_ios_simulator
          flutter -v test integration_test/main_test.dart -d iPhone
