name: CI

on:
  push:

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: /usr/bin/arch -arm64e xcrun simctl list devices booted
        run: /usr/bin/arch -arm64e xcrun simctl list devices booted

      - name: Launch iOS simulator
        run: flutter -v emulators --launch apple_ios_simulator

      - name: Run integration tests
        run: flutter -v test integration_test/main_test.dart -d iPhone
